# Generated by Django 4.1.4 on 2022-12-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipesh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
